version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient
    hostname: mongoclient
    ports:
      - 3300:3000
  streamloots:
    container_name: streamloots
    build:
      context: .
      dockerfile: Dockerfile
    hostname: streamloots
    depends_on:
      - mongo    
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo
    ports:
      - 3000:3000