swagger: "2.0"
info:
  version: 1.0.0
  title: streamloots
  description: Streamloots Card API
basePath: /api/v1
tags:
  - name: Cards
    description: Streamloots card API
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  CardBody:
    type: object
    title: card
    properties:
      id:
        type: string
        example: fe3f7471e8174b86999c32c0288f7e4e
      name:
        type: string
        example: Thor
      owner:
        type: string
        example: 5a50159308f5a800111de759
      image:
        type: string
        example: file.jpg
      limit:
        type: number
        example: 10
      rarity: 
        type: string
        example: Rare
      published:
        type: boolean
        example: true
paths:
  /cards:
    get:
      tags:
        - Cards
      description: Fetch all cards
      responses:
        200:
          description: Returns all cards
    post:
      tags:
        - Cards
      description: Create a new card
      parameters:
        - name: card
          in: body
          description: a card
          required: true
          schema: 
            $ref: "#/definitions/CardBody"
      responses:
        201:
          description: Returns created card

  /cards/{id}:
    get:
      tags:
        - Cards
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the card to retrieve
          type: string
      responses:
        200:
          description: Return the card with the specified id
        404:
          description: Example not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification